name: hawk_control_app
description: Hawk control app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_vlc_player: ^7.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
